//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noktalı_Virgül.Models.VeriTabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HizliProjeEntities9 : DbContext
    {
        public HizliProjeEntities9()
            : base("name=HizliProjeEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblFavoriler> tblFavoriler { get; set; }
        public virtual DbSet<tblKitap> tblKitap { get; set; }
        public virtual DbSet<tblKitapTur> tblKitapTur { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblMesaj> tblMesaj { get; set; }
        public virtual DbSet<tblSatinAlinanlar> tblSatinAlinanlar { get; set; }
        public virtual DbSet<tblSepet> tblSepet { get; set; }
        public virtual DbSet<tblYayinEvi> tblYayinEvi { get; set; }
        public virtual DbSet<tblZiyaretci> tblZiyaretci { get; set; }
        public virtual DbSet<tblPromosyon> tblPromosyon { get; set; }
    
        [DbFunction("HizliProjeEntities9", "FN_AlanlarinKodu")]
        public virtual IQueryable<FN_AlanlarinKodu_Result> FN_AlanlarinKodu(Nullable<int> urunKod)
        {
            var urunKodParameter = urunKod.HasValue ?
                new ObjectParameter("urunKod", urunKod) :
                new ObjectParameter("urunKod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_AlanlarinKodu_Result>("[HizliProjeEntities9].[FN_AlanlarinKodu](@urunKod)", urunKodParameter);
        }
    
        [DbFunction("HizliProjeEntities9", "FN_BunuAlanBunlariAldi")]
        public virtual IQueryable<FN_BunuAlanBunlariAldi_Result> FN_BunuAlanBunlariAldi(Nullable<int> urunKod)
        {
            var urunKodParameter = urunKod.HasValue ?
                new ObjectParameter("urunKod", urunKod) :
                new ObjectParameter("urunKod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_BunuAlanBunlariAldi_Result>("[HizliProjeEntities9].[FN_BunuAlanBunlariAldi](@urunKod)", urunKodParameter);
        }
    
        public virtual ObjectResult<deneme_Result> deneme(Nullable<int> urunKod)
        {
            var urunKodParameter = urunKod.HasValue ?
                new ObjectParameter("urunKod", urunKod) :
                new ObjectParameter("urunKod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<deneme_Result>("deneme", urunKodParameter);
        }
    
        public virtual ObjectResult<EnCokSatisYapanKategori_Result> EnCokSatisYapanKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnCokSatisYapanKategori_Result>("EnCokSatisYapanKategori");
        }
    
        public virtual ObjectResult<Encoksatisyapilanurunler_Result> Encoksatisyapilanurunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Encoksatisyapilanurunler_Result>("Encoksatisyapilanurunler");
        }
    
        public virtual ObjectResult<EnCokSepeteEklenenUrunler_Result> EnCokSepeteEklenenUrunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnCokSepeteEklenenUrunler_Result>("EnCokSepeteEklenenUrunler");
        }
    
        public virtual ObjectResult<GunlukKayitOlanKisiSayisi_Result> GunlukKayitOlanKisiSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukKayitOlanKisiSayisi_Result>("GunlukKayitOlanKisiSayisi");
        }
    
        public virtual ObjectResult<GunlukKitapSatisSayisi_Result> GunlukKitapSatisSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukKitapSatisSayisi_Result>("GunlukKitapSatisSayisi");
        }
    
        public virtual ObjectResult<ister_Result> ister(Nullable<int> urunKod)
        {
            var urunKodParameter = urunKod.HasValue ?
                new ObjectParameter("urunKod", urunKod) :
                new ObjectParameter("urunKod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ister_Result>("ister", urunKodParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamKitapSatis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamKitapSatis");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamKitapSatisGunluk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamKitapSatisGunluk");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamKullaniciKaydi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamKullaniciKaydi");
        }
    }
}
