//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noktalı_Virgül.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromosyon
    {
        public int PromosyonId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<bool> TumUrunler { get; set; }
        public Nullable<int> IndirimOrani { get; set; }
    
        public virtual tblKitap tblKitap { get; set; }
        public virtual tblKitapTur tblKitapTur { get; set; }
    }
}
