//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noktalı_Virgül.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSepet
    {
        public int SepetId { get; set; }
        public Nullable<int> ZiyaretciId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public int UrunId { get; set; }
        public int SepettekiAdet { get; set; }
    
        public virtual tblKitap tblKitap { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblZiyaretci tblZiyaretci { get; set; }
    }
}
