//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noktalı_Virgül.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatinAlinanlar
    {
        public int SatinAlinanID { get; set; }
        public int MusteriID { get; set; }
        public int UrunID { get; set; }
        public int SatinAlmaAdedi { get; set; }
        public Nullable<decimal> UrunBirimFiyati { get; set; }
        public Nullable<decimal> ToplamFiyat { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> SatinAlmaTarihi { get; set; }
    
        public virtual tblKitap tblKitap { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
